const CATALOG = [
  //Аксессуары
  //шарфы
  {
    id: "e1",
    name: "Loro Piana",
    subname: "шарфы/аксессуары",
    size: "30/170см",
    img: "https://i.ibb.co/C598HsF/1-Loro-Piana.jpg",
    price: 26673,
    brand: "Loro Piana",
    type2: "Шарфы",
  },
  {
    id: "e2",
    name: "Brunello Cucinelli",
    subname: "шарфы/аксессуары",
    size: "40/180см",
    img: "https://i.ibb.co/k8hr71J/2-Brunello-Cucinelli.jpg",
    price: 30182,
    brand: "Brunello Cucinelli",
    type2: "Шарфы",
  },
  {
    id: "e3",
    name: "D`uomo Milano",
    subname: "шарфы/аксессуары",
    size: "60/180см",
    img: "https://i.ibb.co/5vFvJ6n/3-D-uono-Milano.jpg",
    price: 4789,
    brand: "D`uomo Milano",
    type2: "Шарфы",
  },
  {
    id: "e4",
    name: "Stefano Ricci",
    subname: "шарфы/аксессуары",
    size: "30/170см",
    img: "https://i.ibb.co/QpnQsj4/4-Stefano-Ricci.jpg",
    price: 20573,
    brand: "Stefano Ricci",
    type2: "Шарфы",
  },
  {
    id: "e5",
    name: "Isaia",
    subname: "шарфы/аксессуары",
    size: "30/170см",
    img: "https://i.ibb.co/r6jYYX8/5-Isaia.jpg",
    price: 30593,
    brand: "Isaia",
    type2: "Шарфы",
  },
  {
    id: "e6",
    name: "Palm Angels",
    subname: "шарфы/аксессуары",
    size: "40/180см",
    img: "https://i.ibb.co/bHTzQQm/6-Palm-Angels.jpg",
    price: 32740,
    brand: "Palm Angels",
    type2: "Шарфы",
  },
  {
    id: "e7",
    name: "Loro Piana",
    subname: "шарфы/аксессуары",
    size: "30/180см",
    img: "https://i.ibb.co/mT8g2K1/7-Loro-Piana-2.jpg",
    price: 25050,
    brand: "Loro Piana",
    type2: "Шарфы",
  },
  {
    id: "e8",
    name: "Brunello Cucinelli",
    subname: "шарфы/аксессуары",
    size: "30/180см",
    img: "https://i.ibb.co/QHKhBRR/8-Brunello-Cucinelli-2.jpg",
    price: 35500,
    brand: "Brunello Cucinelli",
    type2: "Шарфы",
  },
  {
    id: "e9",
    name: "Stefano Ricci",
    subname: "шарфы/аксессуары",
    size: "30/170см",
    img: "https://i.ibb.co/VLRrJV0/9-Stefano-Ricci-2.jpg",
    price: 32000,
    brand: "Stefano Ricci",
    type2: "Шарфы",
  },
  {
    id: "e10",
    name: "Balmain",
    subname: "шарфы/аксессуары",
    size: "40/180см",
    img: "https://i.ibb.co/s6BvbYX/10-Stefano-Ricci-3.jpg",
    price: 15500,
    brand: "Balmain",
    type2: "Шарфы",
  },
  //Очки
  {
    id: "e11",
    name: "Vilebrequin",
    subname: "очки/аксессуары",
    size: "45мм:42мм:130мм",
    img: "https://i.ibb.co/jzpGjGb/1-Vilebrequin.jpg",
    price: 32050,
    brand: "Vilebrequin",
    type2: "Очки",
  },
  {
    id: "e12",
    name: "Stefano Ricci",
    subname: "очки/аксессуары",
    size: "35мм:38мм:130мм",
    img: "https://i.ibb.co/9rVC4r3/2-Stefano-Ricci.jpg",
    price: 45182,
    brand: "Stefano Ricci",
    type2: "Очки",
  },
  {
    id: "e13",
    name: "Gucci",
    subname: "очки/аксессуары",
    size: "32мм:40мм:120мм",
    img: "https://i.ibb.co/BzvJSyg/3-Gucci.jpg",
    price: 50200,
    brand: "Gucci",
    type2: "Очки",
  },
  {
    id: "e14",
    name: "Brunello Cucinelli",
    subname: "очки/аксессуары",
    size: "45мм:42мм:130мм",
    img: "https://i.ibb.co/xzGnyt7/4-Brunello-Cucinelli.jpg",
    price: 22250,
    brand: "Brunello Cucinelli",
    type2: "Очки",
  },
  {
    id: "e15",
    name: "Balmain",
    subname: "очки/аксессуары",
    size: "38мм:40мм:130мм",
    img: "https://i.ibb.co/ky7hVwG/5-Balmain.jpg",
    price: 15095,
    brand: "Balmain",
    type2: "Очки",
  },
  {
    id: "e16",
    name: "Off-White",
    subname: "очки/аксессуары",
    size: "38мм:40мм:130мм",
    img: "https://i.ibb.co/SKNDVcp/6-Off-White.jpg",
    price: 32740,
    brand: "Off-White",
    type2: "Очки",
  },
  {
    id: "e17",
    name: "Stefano Ricci",
    subname: "очки/аксессуары",
    size: "38мм:40мм:130мм",
    img: "https://i.ibb.co/f4sGpMt/8-Stefano-Ricci-2.jpg",
    price: 22850,
    brand: "Stefano Ricci",
    type2: "Очки",
  },
  {
    id: "e18",
    name: "Off-White",
    subname: "очки/аксессуары",
    size: "40мм:40мм:120мм",
    img: "https://i.ibb.co/N2Hs0Pn/7-Off-White-2.jpg",
    price: 30500,
    brand: "Off-White",
    type2: "Очки",
  },
  {
    id: "e19",
    name: "Balmain",
    subname: "очки/аксессуары",
    size: "45мм:42мм:130мм",
    img: "https://i.ibb.co/p2H0hZ6/10-Balmain-2.jpg",
    price: 18900,
    brand: "Balmain",
    type2: "Очки",
  },
  {
    id: "e20",
    name: "Stefano Ricci",
    subname: "очки/аксессуары",
    size: "40мм:40мм:120мм",
    img: "https://i.ibb.co/DWBLCbc/9-Stefano-Ricci-3.jpg",
    price: 25050,
    brand: "Stefano Ricci",
    type2: "Очки",
  },
  {
    id: "e21",
    name: "Brunello Cucinelli",
    subname: "очки/аксессуары",
    size: "40мм:42мм:130мм",
    img: "https://i.ibb.co/2YykrTc/12-Brunello-Cucinelli-2.jpg",
    price: 15450,
    brand: "Brunello Cucinelli",
    type2: "Очки",
  },
  {
    id: "e22",
    name: "Balmain",
    subname: "очки/аксессуары",
    size: "45мм:42мм:130мм",
    img: "https://i.ibb.co/thjN0Wy/11-Balmain-3.jpg",
    price: 22532,
    brand: "Balmain",
    type2: "Очки",
  },

  //Головные уборы
  {
    id: "e23",
    name: "Valentino",
    subname: "головные уборы/кепки/аксессуары",
    size: ["S", "M"],
    img: "https://i.ibb.co/MP8JPnc/1-Valentino.jpg",
    price: 38532,
    brand: "Valentino",
    type2: "Головные уборы",
  },
  {
    id: "e24",
    name: "Vilebrequin",
    subname: "головные уборы/шляпы/аксессуары",
    size: ["S", "M", "L"],
    img: "https://i.ibb.co/frrnx50/2-Vilebrequin.jpg",
    price: 26050,
    brand: "Vilebrequin",
    type2: "Головные уборы",
  },
  {
    id: "e25",
    name: "Marcelo-Burlon",
    subname: "головные уборы/кепки/аксессуары",
    size: ["S", "L"],
    img: "https://i.ibb.co/2kXmQk3/3-Marcelo-Burlon.jpg",
    price: 18532,
    brand: "Marcelo-Burlon",
    type2: "Головные уборы",
  },
  {
    id: "e26",
    name: "Alexander McQueen",
    subname: "головные уборы/панамки/аксессуары",
    size: ["M", "L"],
    img: "https://i.ibb.co/Bt0MgS1/4-Alexander-MCQueen.jpg",
    price: 33232,
    brand: "Alexander McQueen",
    type2: "Головные уборы",
  },
  {
    id: "e27",
    name: "Dolce&Gabbana",
    subname: "головные уборы,кепки/аксессуары",
    size: ["S", "M", "L"],
    img: "https://i.ibb.co/3S1V6wF/5-Dolce-Gabbana.jpg",
    price: 48532,
    brand: "Dolce&Gabbana",
    type2: "Головные уборы",
  },
  {
    id: "e28",
    name: "D`uomo Milano",
    subname: "головные уборы/шапки/аксессуары",
    size: ["S", "L"],
    img: "https://i.ibb.co/hYBC9bg/6-D-uomo-Milano.jpg",
    price: 22532,
    brand: "D`uomo Milano",
    type2: "Головные уборы",
  },
  {
    id: "e29",
    name: "Off-White",
    subname: "головные уборы/кепки/аксессуары",
    size: ["S", "M", "L"],
    img: "https://i.ibb.co/5Rfj8MK/7-Off-White.jpg",
    price: 45232,
    brand: "Off-White",
    type2: "Головные уборы",
  },
  {
    id: "e30",
    name: "Off-White",
    subname: "головные уборы/кепки/аксессуары",
    size: ["S", "M"],
    img: "https://i.ibb.co/VtZCXJj/8-Off-White-2.jpg",
    price: 38532,
    brand: "Off-White",
    type2: "Головные уборы",
  },
  //Одежда
  //Рубашки
  {
    id: "e31",
    name: "Isaia",
    subname: "рубашки/одежда",
    size: ["S", "M", "L"],
    img: "https://i.ibb.co/xzj7b5M/9-Isaia.jpg",
    price: 18250,
    brand: "Isaia",
    type: "Рубашки",
  },
  {
    id: "e32",
    name: "Dolce&Gabbana",
    subname: "рубашки/одежда",
    size: ["S", "L"],
    img: "https://i.ibb.co/YQctc7V/11-Dolce-Gabbana.jpg",
    price: 42000,
    brand: "Dolce&Gabbana",
    type: "Рубашки",
  },
  {
    id: "e33",
    name: "Loro Piana",
    subname: "рубашки/одежда",
    size: ["M", "L"],
    img: "https://i.ibb.co/BKfyvY4/14-Loro-Piana-2.jpg",
    price: 20150,
    brand: "Loro Piana",
    type: "Рубашки",
  },
  {
    id: "e34",
    name: "Brunello Cucinelli",
    subname: "рубашки/одежда",
    size: ["S", "M"],
    img: "https://i.ibb.co/dgLhXHB/1-Brunello-Cucinelli.jpg",
    price: 32002,
    brand: "Brunello Cucinelli",
    type: "Рубашки",
  },
  {
    id: "e35",
    name: "Vilebrequin",
    subname: "рубашки/одежда",
    size: ["S", "M", "L"],
    img: "https://i.ibb.co/z4VH81j/3-Vilebrequin.jpg",
    price: 12050,
    brand: "Vilebrequin",
    type: "Рубашки",
  },
  {
    id: "e36",
    name: "Canali",
    subname: "рубашки/одежда",
    size: ["S", "L"],
    img: "https://i.ibb.co/svX7xyM/6-Canali.jpg",
    price: 24355,
    brand: "Canali",
    type: "Рубашки",
  },
  {
    id: "e37",
    name: "Off-White",
    subname: "рубашки/одежда",
    size: ["M", "L"],
    img: "https://i.ibb.co/PQTpfcJ/7-Off-White.jpg",
    price: 34502,
    brand: "Off-White",
    type: "Рубашки",
  },
  {
    id: "e38",
    name: "Off-White",
    subname: "рубашки/одежда",
    size: ["S", "M", "L"],
    img: "https://i.ibb.co/ZJrB1Dk/8-Off-White-2.jpg",
    price: 41032,
    brand: "Off-White",
    type: "Рубашки",
  },
  //Худи
  {
    id: "e39",
    name: "Heron Preston",
    subname: "худи/одежда",
    size: ["S", "M", "L"],
    img: "https://i.ibb.co/7RF4kr9/6-Heron-Preston.jpg",
    price: 39000,
    brand: "Heron Preston",
    type: "Худи",
  },
  {
    id: "e40",
    name: "Dolce&Gabbana",
    subname: "худи/одежда",
    size: ["S", "L"],
    img: "https://i.ibb.co/MkWC39g/9-Docle-Gabbana-2.jpg",
    price: 55350,
    brand: "Dolce&Gabbana",
    type: "Худи",
  },
  {
    id: "e41",
    name: "Hero Preston",
    subname: "худи/одежда",
    size: ["S", "M", "L"],
    img: "https://i.ibb.co/0QFYg7X/12-Heron-Preston-2.jpg",
    price: 25500,
    brand: "Hero Preston",
    type: "Худи",
  },
  {
    id: "e42",
    name: "Balmain",
    subname: "худи/одежда",
    size: ["M", "L"],
    img: "https://i.ibb.co/tmqBQ2r/16-Balmain-2.jpg",
    price: 41000,
    brand: "Balmain",
    type: "Худи",
  },
  {
    id: "e43",
    name: "Dolce&Gabbana",
    subname: "худи/одежда",
    size: ["S", "M"],
    img: "https://i.ibb.co/HCRf37r/1-Dolce-Gabbana.jpg",
    price: 45032,
    brand: "Dolce&Gabbana",
    type: "Худи",
  },
  {
    id: "e44",
    name: "Off-White",
    subname: "худи/одежда",
    size: ["S", "M", "L"],
    img: "https://i.ibb.co/XsnfsMh/4-Off-White.jpg",
    price: 33333,
    brand: "Off-White",
    type: "Худи",
  },
  //Жилеты
  {
    id: "e45",
    name: "Isaia",
    subname: "жилеты/одежда",
    size: ["S", "L"],
    img: "https://i.ibb.co/169ydXD/7-Isaia.jpg",
    price: 35500,
    brand: "Isaia",
    type: "Жилеты",
  },
  {
    id: "e46",
    name: "Brunello Cucinelli",
    subname: "жилеты/одежда",
    size: ["M", "L"],
    img: "https://i.ibb.co/0yxRyJd/8-Brunello-Cucinelli-2.jpg",
    price: 29050,
    brand: "Brunello Cucinelli",
    type: "Жилеты",
  },
  {
    id: "e47",
    name: "Stefano Ricci",
    subname: "жилеты/одежда",
    size: ["S", "M"],
    img: "https://i.ibb.co/HtXhZDV/12-Stefano-Ricci-2.jpg",
    price: 26200,
    brand: "Stefano Ricci",
    type: "Жилеты",
  },
  {
    id: "e48",
    name: "Isaia",
    subname: "жилеты/одежда",
    size: ["S", "M", "L"],
    img: "https://i.ibb.co/QXRdY2C/13-Isaia-2.jpg",
    price: 30000,
    brand: "Isaia",
    type: "Жилеты",
  },
  {
    id: "e49",
    name: "Brunello Cucinelli",
    subname: "жилеты/одежда",
    size: ["S", "M", "L"],
    img: "https://i.ibb.co/bgv8Hrr/14-Brunello-Cucinelli-3.jpg",
    price: 36100,
    brand: "Brunello Cucinelli",
    type: "Жилеты",
  },
  {
    id: "e50",
    name: "Stefano Ricci",
    subname: "жилеты/одежда",
    size: ["M", "L"],
    img: "https://i.ibb.co/BLj47bJ/4-Stefano-Ricci.jpg",
    price: 42000,
    brand: "Stefano Ricci",
    type: "Жилеты",
  },
  //Обувь
  //Сапоги
  {
    id: "e51",
    name: "Brunello Cucinelli",
    subname: "сапоги/обувь",
    size: ["40см", "47.5см"],
    img: "https://i.ibb.co/Dwgb0hS/3-Brunello-Cucinelli.jpg",
    price: 40000,
    brand: "Brunello Cucinelli",
    type4: "Сапоги",
  },
  {
    id: "e52",
    name: "Off-White",
    subname: "сапоги/обувь",
    size: ["39см", "44см", "47.5см"],
    img: "https://i.ibb.co/WBys8cX/4-Off-White.jpg",
    price: 42500,
    brand: "Off-White",
    type4: "Сапоги",
  },
  {
    id: "e53",
    name: "Enrico Mandelli",
    subname: "сапоги/обувь",
    size: ["39см", "42см"],
    img: "https://i.ibb.co/yFyfXxp/5-Enrico-Mandelli.jpg",
    price: 24200,
    brand: "Enrico Mandelli",
    type4: "Сапоги",
  },
  {
    id: "e54",
    name: "Loro Piana",
    subname: "сапоги/обувь",
    size: ["46см", "40см", "47.5см"],
    img: "https://i.ibb.co/1252VRB/6-Loro-Piana.jpg",
    price: 52500,
    brand: "Loro Piana",
    type4: "Сапоги",
  },
  {
    id: "e55",
    name: "Enrico Mandelli",
    subname: "сапоги/обувь",
    size: ["39см", "44см"],
    img: "https://i.ibb.co/Dbnsdp2/9-Enrico-Mandelli-2.jpg",
    price: 42000,
    brand: "Enrico Mandelli",
    type4: "Сапоги",
  },
  {
    id: "e56",
    name: "Stefano Ricci",
    subname: "сапоги/обувь",
    size: ["39см", "40см", "47.5см"],
    img: "https://i.ibb.co/XtSG20Z/13-Stefana-Ricci.jpg",
    price: 48150,
    brand: "Stefano Ricci",
    type4: "Сапоги",
  },
  {
    id: "e57",
    name: "Moorer",
    subname: "сапоги/обувь",
    size: ["40см", "42см", "46см"],
    img: "https://i.ibb.co/yP80Fys/16-Moorer-2.jpg",
    price: 10200,
    brand: "Moorer",
    type4: "Сапоги",
  },
  {
    id: "e58",
    name: "Doucal`s",
    subname: "сапоги/обувь",
    size: ["39см", "44см", "47.5см"],
    img: "https://i.ibb.co/7vwhF1k/1-Doucal-s.jpg",
    price: 5500,
    brand: "Doucal`s",
    type4: "Сапоги",
  },
  //Туфли
  {
    id: "e59",
    name: "Doucal`s",
    subname: "туфли/обувь",
    size: ["39см", "44см", "47.5см"],
    img: "https://i.ibb.co/jV5tcTD/2-Doucal-s.jpg",
    price: 32500,
    brand: "Doucal`s",
    type4: "Туфли",
  },
  {
    id: "e60",
    name: "Stefano Ricci",
    subname: "туфли/обувь",
    size: ["47.5см"],
    img: "https://i.ibb.co/cFfNbjV/3-Stefano-Ricci.jpg",
    price: 55500,
    brand: "Stefano Ricci",
    type4: "Туфли",
  },
  {
    id: "e61",
    name: "Santoni",
    subname: "туфли/обувь",
    size: ["40см", "42см"],
    img: "https://i.ibb.co/Gtn8DdH/6-Santoni.jpg",
    price: 15200,
    brand: "Santoni",
    type4: "Туфли",
  },
  {
    id: "e62",
    name: "Brunello Cucinelli",
    subname: "туфли/обувь",
    size: ["39см", "40см", "47.5см"],
    img: "https://i.ibb.co/CJL02dL/7-Brunello-Cucinelli.jpg",
    price: 28220,
    brand: "Brunello Cucinelli",
    type4: "Туфли",
  },
  {
    id: "e63",
    name: "Brunello Cucinelli",
    subname: "туфли/обувь",
    size: ["39см", "44см", "46см", "47.5см"],
    img: "https://i.ibb.co/jbP3Lfw/14-Brunello-Cucinelli-3.jpg",
    price: 50200,
    brand: "Brunello Cucinelli",
    type4: "Туфли",
  },
  {
    id: "e64",
    name: "Kiton",
    subname: "туфли/обувь",
    size: ["46см"],
    img: "https://i.ibb.co/4Tgr4Kb/1-Kiton.jpg",
    price: 12500,
    brand: "Kiton",
    type4: "Туфли",
  },
  //Кросовки
  {
    id: "e65",
    name: "Tom Ford",
    subname: "кросовки/обувь",
    size: ["39см", "44см", "47.5см"],
    img: "https://i.ibb.co/rHrzJ01/14-Tom-Ford.jpg",
    price: 22500,
    brand: "Tom Ford",
    type4: "Кроссовки",
  },
  {
    id: "e66",
    name: "Stefano Ricci",
    subname: "кросовки/обувь",
    size: ["42см", "44см"],
    img: "https://i.ibb.co/0j1TTTC/4-Stefano-Ricci.jpg",
    price: 34750,
    brand: "Stefano Ricci",
    type4: "Кроссовки",
  },
  {
    id: "e67",
    name: "Kiton",
    subname: "кросовки/обувь",
    size: ["39см", "46см"],
    img: "https://i.ibb.co/TRx0ZCd/6-Kiton.jpg",
    price: 18100,
    brand: "Kiton",
    type4: "Кроссовки",
  },
  {
    id: "e68",
    name: "Off-White",
    subname: "кросовки/обувь",
    size: ["46см", "47.5см"],
    img: "https://i.ibb.co/Vm99MBh/7-Off-White.jpg",
    price: 42200,
    brand: "Off-White",
    type4: "Кроссовки",
  },
  {
    id: "e69",
    name: "Off-White",
    subname: "кросовки/обувь",
    size: ["39см", "40см", "44см", "47.5см"],
    img: "https://i.ibb.co/6JzvzQ1/8-Off-White-2.jpg",
    price: 52500,
    brand: "Off-White",
    type4: "Кроссовки",
  },
  //Сумки
  //Поясные сумки
  {
    id: "e70",
    name: "Santoni",
    subname: "поясные сумки",
    size: ["ONE SIZE"],
    img: "https://i.ibb.co/nnWTHz7/10-Santoni.jpg",
    price: 12100,
    brand: "Santoni",
    type3: "Поясные сумки",
  },
  {
    id: "e71",
    name: "Dolce&Gabbana",
    subname: "поясные сумки",
    size: ["ONE SIZE"],
    img: "https://i.ibb.co/XWh515G/2-Dolce-Gabbana.jpg",
    price: 55000,
    brand: "Dolce&Gabbana",
    type3: "Поясные сумки",
  },
  {
    id: "e72",
    name: "Palm Angels",
    subname: "поясные сумки",
    size: ["ONE SIZE"],
    img: "https://i.ibb.co/1rGHVTp/3-Palm-Angels.jpg",
    price: 32550,
    brand: "Palm Angels",
    type3: "Поясные сумки",
  },
  {
    id: "73",
    name: "Alexander McQueen",
    subname: "поясные сумки",
    size: ["ONE SIZE"],
    img: "https://i.ibb.co/x3zxYdN/4-Alexander-MCQueen.jpg",
    price: 42350,
    brand: "Alexander McQueen",
    type3: "Поясные сумки",
  },
  {
    id: "74",
    name: "Off-White",
    subname: "поясные сумки",
    size: ["ONE SIZE"],
    img: "https://i.ibb.co/x6N782Y/7-Off-White-2.jpg",
    price: 23200,
    brand: "Off-White",
    type3: "Поясные сумки",
  },
  //Портфели/Рюкзаки
  {
    id: "75",
    name: "Serapian",
    subname: "портфели/рюкзаки",
    size: ["ONE SIZE"],
    img: "https://i.ibb.co/t89gycw/8-Serapian-2.jpg",
    price: 57200,
    brand: "Serapian",
    type3: "Портфели/Рюкзаки",
  },
  {
    id: "76",
    name: "Stefano Ricci",
    subname: "портфели/рюкзаки",
    size: ["ONE SIZE"],
    img: "https://i.ibb.co/qdms0n0/9-Stefani-Ricci.jpg",
    price: 94500,
    brand: "Stefano Ricci",
    type3: "Портфели/Рюкзаки",
  },
  {
    id: "77",
    name: "Marcelo Burlon",
    subname: "поясные сумки",
    size: ["ONE SIZE"],
    img: "https://i.ibb.co/Lgr9bLq/17-Marcelo-Burlon.jpg",
    price: 86450,
    brand: "Marcelo Burlon",
    type3: "Портфели/Рюкзаки",
  },
  {
    id: "78",
    name: "Serapian",
    subname: "портфели/рюкзаки",
    size: ["ONE SIZE"],
    img: "https://i.ibb.co/RS2R3nP/2-Serapian.jpg",
    price: 58250,
    brand: "Serapian",
    type3: "Портфели/Рюкзаки",
  },
  {
    id: "79",
    name: "Alexander McQueen",
    subname: "портфели/рюкзаки",
    size: ["ONE SIZE"],
    img: "https://i.ibb.co/26sL3DQ/3-Alexander-MCQueen.jpg",
    price: 120500,
    brand: "Alexander McQueen",
    type3: "Портфели/Рюкзаки",
  },
  {
    id: "80",
    name: "Valentino",
    subname: "портфели/рюкзаки",
    size: ["ONE SIZE"],
    img: "https://i.ibb.co/sqJ1K01/4-Valentino.jpg",
    price: 96750,
    brand: "Valentino",
    type3: "Портфели/Рюкзаки",
  },
  //Наплечные сумки
  {
    id: "81",
    name: "Serapian",
    subname: "наплечные сумки",
    size: ["ONE SIZE"],
    img: "https://i.ibb.co/j53XRYK/12-Serapian-2.jpg",
    price: 34700,
    brand: "Serapian",
    type3: "Наплечные сумки",
  },
  {
    id: "82",
    name: "Serapian",
    subname: "наплечные сумки",
    size: ["ONE SIZE"],
    img: "https://i.ibb.co/pXFZLcj/2-Serapian.jpg",
    price: 29400,
    brand: "Serapian",
    type3: "Наплечные сумки",
  },
  {
    id: "83",
    name: "Tom Ford",
    subname: "наплечные сумки",
    size: ["ONE SIZE"],
    img: "https://i.ibb.co/ZN0hz0Z/4-Tom-Ford.jpg",
    price: 55350,
    brand: "Tom Ford",
    type3: "Наплечные сумки",
  },
  {
    id: "84",
    name: "Palm Angels",
    subname: "наплечные сумки",
    size: ["ONE SIZE"],
    img: "https://i.ibb.co/NSRr8vz/7-Palm-Angels.jpg",
    price: 110500,
    brand: "Palm Angels",
    type3: "Наплечные сумки",
  },
];
